/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      id: "pbc_books",
      name: "books",
      type: "base",
      system: false,
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          hidden: false,
          id: "text3208210256",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text_book_title",
          max: 0,
          min: 0,
          name: "title",
          pattern: "",
          presentable: true,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text_book_author",
          max: 0,
          min: 0,
          name: "author",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text_book_description",
          max: 0,
          min: 0,
          name: "description",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          hidden: false,
          id: "file_book_cover",
          maxSelect: 1,
          maxSize: 5242880,
          mimeTypes: ["image/jpeg", "image/png", "image/webp"],
          name: "cover_image",
          presentable: false,
          protected: false,
          required: false,
          system: false,
          thumbs: ["200x300"],
          type: "file",
        },
        {
          hidden: false,
          id: "select_book_status",
          maxSelect: 1,
          name: "status",
          presentable: false,
          required: true,
          system: false,
          type: "select",
          values: ["reading", "completed"],
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text_book_purchase_link",
          max: 0,
          min: 0,
          name: "purchase_link",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text_book_start_date",
          max: 0,
          min: 0,
          name: "start_date",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text_book_end_date",
          max: 0,
          min: 0,
          name: "end_date",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          hidden: false,
          id: "number_book_sort_order",
          max: null,
          min: null,
          name: "sort_order",
          onlyInt: true,
          presentable: false,
          required: false,
          system: false,
          type: "number",
        },
        {
          hidden: false,
          id: "autodate_created",
          name: "created",
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate_updated",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: "autodate",
        },
      ],
      indexes: [],
      listRule: "",
      viewRule: "",
      createRule: '@request.auth.id != "" && @request.auth.role = "moderator"',
      updateRule: '@request.auth.id != "" && @request.auth.role = "moderator"',
      deleteRule: '@request.auth.id != "" && @request.auth.role = "moderator"',
    });

    return app.save(collection);
  },
  (app) => {
    const collection = app.findCollectionByNameOrId("pbc_books");
    return app.delete(collection);
  },
);
